package net.bradmont.openmpd.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CONTACT_SUBLIST".
 */
public class ContactSublist {

    private Long id;
    private String tntPeopleId;
    private String listName;

    public ContactSublist() {
    }

    public ContactSublist(Long id) {
        this.id = id;
    }

    public ContactSublist(Long id, String tntPeopleId, String listName) {
        this.id = id;
        this.tntPeopleId = tntPeopleId;
        this.listName = listName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTntPeopleId() {
        return tntPeopleId;
    }

    public void setTntPeopleId(String tntPeopleId) {
        this.tntPeopleId = tntPeopleId;
    }

    public String getListName() {
        return listName;
    }

    public void setListName(String listName) {
        this.listName = listName;
    }

}
