package net.bradmont.openmpd.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GIVING_SUMMARY_CACHE".
 */
public class GivingSummaryCache {

    private String month;
    private String base;
    private String regular;
    private String frequent;
    private String special;

    public GivingSummaryCache() {
    }

    public GivingSummaryCache(String month, String base, String regular, String frequent, String special) {
        this.month = month;
        this.base = base;
        this.regular = regular;
        this.frequent = frequent;
        this.special = special;
    }

    public String getMonth() {
        return month;
    }

    public void setMonth(String month) {
        this.month = month;
    }

    public String getBase() {
        return base;
    }

    public void setBase(String base) {
        this.base = base;
    }

    public String getRegular() {
        return regular;
    }

    public void setRegular(String regular) {
        this.regular = regular;
    }

    public String getFrequent() {
        return frequent;
    }

    public void setFrequent(String frequent) {
        this.frequent = frequent;
    }

    public String getSpecial() {
        return special;
    }

    public void setSpecial(String special) {
        this.special = special;
    }

}
