package net.bradmont.openmpd.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "QUICK_MESSAGE".
 */
public class QuickMessage {

    private Long id;
    private String name;
    private String subject;
    private String body;
    private java.util.Date notificationType;
    private Boolean customized;

    public QuickMessage() {
    }

    public QuickMessage(Long id) {
        this.id = id;
    }

    public QuickMessage(Long id, String name, String subject, String body, java.util.Date notificationType, Boolean customized) {
        this.id = id;
        this.name = name;
        this.subject = subject;
        this.body = body;
        this.notificationType = notificationType;
        this.customized = customized;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public java.util.Date getNotificationType() {
        return notificationType;
    }

    public void setNotificationType(java.util.Date notificationType) {
        this.notificationType = notificationType;
    }

    public Boolean getCustomized() {
        return customized;
    }

    public void setCustomized(Boolean customized) {
        this.customized = customized;
    }

}
