package net.bradmont.openmpd.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CONTACT_SUBLIST".
 */
public class ContactSublist {

    private Long id;
    private String contact_id;
    private String listName;

    public ContactSublist() {
    }

    public ContactSublist(Long id) {
        this.id = id;
    }

    public ContactSublist(Long id, String contact_id, String listName) {
        this.id = id;
        this.contact_id = contact_id;
        this.listName = listName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getContact_id() {
        return contact_id;
    }

    public void setContact_id(String contact_id) {
        this.contact_id = contact_id;
    }

    public String getListName() {
        return listName;
    }

    public void setListName(String listName) {
        this.listName = listName;
    }

}
