package net.bradmont.openmpd.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LOG".
 */
public class Log {

    private Long id;
    private String msg1;
    private String msg2;
    private String msg3;

    public Log() {
    }

    public Log(Long id) {
        this.id = id;
    }

    public Log(Long id, String msg1, String msg2, String msg3) {
        this.id = id;
        this.msg1 = msg1;
        this.msg2 = msg2;
        this.msg3 = msg3;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMsg1() {
        return msg1;
    }

    public void setMsg1(String msg1) {
        this.msg1 = msg1;
    }

    public String getMsg2() {
        return msg2;
    }

    public void setMsg2(String msg2) {
        this.msg2 = msg2;
    }

    public String getMsg3() {
        return msg3;
    }

    public void setMsg3(String msg3) {
        this.msg3 = msg3;
    }

}
